local config = require("chaplet.config")

describe("chaplet.config", function()
  before_each(function()
    config.setup()
  end)

  it("exposes documented defaults", function()
    assert.equals("bd", config.defaults.bd_program)
    assert.is_true(config.defaults.auto_refresh)
    assert.equals(5, config.defaults.refresh_interval)
    assert.equals(2, config.defaults.refresh_delay)
    assert.equals("<leader>b", config.defaults.keymap_prefix)
    assert.equals(28, config.defaults.graph.x_gap)
    assert.equals(40, config.defaults.graph.y_gap)
    assert.equals(28, config.defaults.graph.node_h)
    assert.equals(28, config.defaults.graph.title_max)
    assert.equals(8, config.defaults.graph.pad)
    assert.equals(16, config.defaults.graph.margin)
    assert.equals(20, config.defaults.graph.text_title_max)
    assert.is_false(config.defaults.graph.text_align)
    assert.is_nil(config.defaults.graph.text_lane_max)
  end)

  it("deep merges graph overrides", function()
    config.setup({ graph = { x_gap = 99 } })

    assert.equals(99, config.get("graph.x_gap"))
    assert.equals(40, config.get("graph.y_gap"))
  end)

  it("rejects unknown top-level options", function()
    assert.has_error(function()
      config.setup({ unknown = true })
    end, "chaplet: unknown option unknown")
  end)

  it("looks up dotted paths", function()
    assert.equals(28, config.get("graph.node_h"))
    assert.is_nil(config.get("graph.missing"))
    assert.is_nil(config.get("missing.path"))
  end)
end)
